version: '3.1'

services:
  database-Mariadb:
    container_name: 'mariaDB'
    image: mariadb:latest
    hostname: mydatabase
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
  spring-application:
    depends_on:
      - database-Mariadb
    container_name: app
#    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 8080:8888
    command: ["./wait-for-it.sh", "database-Mariadb:3306"]
    environment:
      - mariadb_HOST=database-Mariadb
#      - "SPRING_DATASOURCE_URL=jdbc:mariadb://database-Mariadb:3306/mydatabase"





